blank_issues_enabled: false
contact_links:
  - name: Questions? Join the Discord channel
    url: https://discord.com/channels/686053708261228577/931008597557649410
    about: 'Join the #minimal channel in the official Obsidian Discord'
  - name: Minimal Documentation
    url: https://minimal.guide/Help
    about: More details about getting help with Minimal